### ISSUE TITLE
Does it work for Python 3?

### ISSUE THREAD

**Issue by ayharano** [computer-lab/django-rest-framework-roles#1]
Hello there.

I read the available code today and it seems very neat for the purpose of "RESTfully" defining roles.

I went to project's PyPI page and it's in Python 2.7 Category. I would like to know if there is any issues related to python 3 which could break (unicode, for example).

Thanks in advance for the reusable app and the very useful article about how to use it.

**Comment by r1b** [comment]
Hi @ayharano,

I haven't had a chance to test with python3 - reviewing the code, I think it should be OK. If you find that it works for you I would be happy to add the python3 category and test against python3 moving forward.

**Comment by najamansari** [comment]
I'm using it without any issues in Python 3.6

**Comment by r1b** [comment]
Thanks @najamansari - closing
