### ISSUE TITLE
What should be ROLE_REGISTRY?

### ISSUE THREAD

**Issue by ayharano** [computer-lab/django-rest-framework-roles#2]
Hello there.

Reading the README.rst file and trying to understand the usage, one doubt arose:

> For example, let’s say you have three groups named Takers, Leavers & Gods. Let’s also say you included "get_queryset" in the ROLE_REGISTRY.

I searched into django-rest-framework-roles using github's interface and I couldn't find any references to ROLE_REGISTRY besides the previous quoting. How can I set the Roles which will be used in a view?

Thanks in advance.

**Comment by r1b** [comment]
Hi @ayharano,

Forgive me - that is a typo. It should be `VIEWSET_METHOD_REGISTRY`. Will fix shortly.

> How can I set the Roles which will be used in a view?

The roles available in each view are set with `ROLE_GROUPS`. By default, this is all of the groups in your application.
